schema:
  - card:
      appName: Blog - Descola
      version: "1.0.0"
      brandDescription: A Descola é uma escola de cursos online que cria grandes experiências de aprendizagem para transformar as pessoas ao longo de suas vidas. Selecionamos temas e professores e construímos conteúdos para que você desenvolva Power Skills.
      brandurl: https://descola.org/
      brandName: Descola
      keywords:
        - key: descola
        - key: cursos
        - key: curso online
        - key: power skills
        - key: soft skills
        - key: habilidades
        - key: escola online
      sameAs:
        facebook: https://www.facebook.com/descolasp/
        instagram: https://www.instagram.com/descolagram/
        linkedIn: https://br.linkedin.com/school/descola
        youtube: https://www.youtube.com/c/DescolaOrg
      alternateName: a
      potentialAction: Learning
      telephone: "+551130420043"
      contactType: Serviço Ao Cliente
      email: descola@descola.com.br
      inLanguage: 'pt-BR'
      datePublished: 05 de março de 2022
