name: Ambiente de testes - boilerplate
on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Obtém o código-fonte e realiza a construção da aplicação.
    runs-on: self-hosted
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      ## construindo::composer
      - name: Executando a construção dos assetsS
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          command: composer create-project --prefer-dist wordplate/wordplate headlessCMS
